### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by pohmelie** [atom-minimap/minimap-highlight-selected#11]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Ubuntu 14.04.2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.9.4

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app.asar/src/decoration.js:135

TypeError: undefined is not a function
  at Decoration.module.exports.Decoration.setProperties (/usr/share/atom/resources/app.asar/src/decoration.js:135:28)
  at new Decoration (/usr/share/atom/resources/app.asar/src/decoration.js:58:12)
  at Minimap.module.exports.DecorationManagement.decorateMarker (/home/poh/.atom/packages/minimap/lib/mixins/decoration-management.coffee:203:22)
  at FakeEditor.(anonymous function) [as decorateMarker] (/home/poh/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:25:30)
  at /home/poh/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:73:31
  at TextBuffer.module.exports.TextBuffer.scanInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:837:9)
  at TextEditor.module.exports.TextEditor.scanInBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:2079:26)
  at FakeEditor.(anonymous function) [as scanInBufferRange] (/home/poh/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:18:30)
  at MinimapHighlightSelectedView.handleSelection (/home/poh/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:68:14)
  at MinimapHighlightSelectedView.handleSelection (/home/poh/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
  at /home/poh/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:93:12
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.selectionRangeChanged (/usr/share/atom/resources/app.asar/src/text-editor.js:2066:27)
  at Selection.module.exports.Selection.screenRangeChanged (/usr/share/atom/resources/app.asar/src/selection.js:877:26)
  at /usr/share/atom/resources/app.asar/src/selection.js:43:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/usr/share/atom/resources/app.asar/src/marker.js:270:27)
  at /usr/share/atom/resources/app.asar/src/marker.js:65:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:400:20)
  at Marker.module.exports.Marker.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:345:12)
  at Marker.module.exports.Marker.setRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:108:19)
  at Marker.module.exports.Marker.setBufferRange (/usr/share/atom/resources/app.asar/src/marker.js:137:32)
  at /usr/share/atom/resources/app.asar/src/selection.js:117:24
  at Selection.module.exports.Selection.modifySelection (/usr/share/atom/resources/app.asar/src/selection.js:906:7)
  at Selection.module.exports.Selection.setBufferRange (/usr/share/atom/resources/app.asar/src/selection.js:110:19)
  at Selection.module.exports.Selection.selectWord (/usr/share/atom/resources/app.asar/src/selection.js:386:12)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/usr/share/atom/resources/app.asar/src/text-editor-component.js:552:42)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
     -9:46.2.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -9:45.3.0 core:save (atom-text-editor.editor.is-focused)
     -9:40.4.0 core:close (atom-text-editor.editor.is-focused)
     -9:39.9.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -8:34.9.0 application:new-file (atom-pane.pane.active)
  2x -8:33.7.0 core:save (atom-text-editor.editor.is-focused)
     -8:24.9.0 run-in-terminal:start-terminal-here (atom-text-editor.editor.is-focused)
  2x -2:29.7.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -2:28.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:57.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:34.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "projectHome": "/home/poh/pro",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "minimap": {
    "plugins": {
      "highlight-selected": true
    },
    "displayPluginsControls": false
  }
}
```

### Installed Packages

```coffee
# User
highlight-line, v0.10.2
highlight-selected, v0.9.3
language-lua, v0.9.3
linter, v0.12.7
linter-pep8, v0.2.0
minimap, v4.9.4
minimap-highlight-selected, v4.3.0
run-in-terminal, v0.2.2

# Dev
No dev packages
```

It says that this is minimap issue, but when I turn minimap-highlight-selected error is gone. So, maybe, this issue should be here.

**Comment by pohmelie** [comment]
Oh, my bad, I forgot about restart after update minimap package. :grimacing:

**Comment by abe33** [comment]
@pohmelie Thanks for the feedback :), there's still some weird behavior after updates, like the previous code still being executed.
