### ISSUE TITLE
Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by Alchiadus** [atom-minimap/minimap-highlight-selected#16]
Receiving the following error on Atom `1.2.0-dev-ca39c10`:

```
Uncaught (in promise) TypeError: atom.packages.activatePackage(...).then(...).fail is not a function
  at C:\Users\Philippe\.atom\packages\minimap-highlight-selected\node_modules\atom-utils\lib\atom-utils.js:28:14
  at Array.forEach (native)
  at C:\Users\Philippe\.atom\packages\minimap-highlight-selected\node_modules\atom-utils\lib\atom-utils.js:24:25
  at module.exports.requirePackages (C:\Users\Philippe\.atom\packages\minimap-highlight-selected\node_modules\atom-utils\lib\atom-utils.js:8:14)
  at MinimapHighlightSelected.consumeMinimapServiceV1 (C:\Users\Philippe\.atom\packages\minimap-highlight-selected\lib\minimap-highlight-selected.coffee:12:5)
  at Provider.module.exports.Provider.provide (C:\Applications\AtomDev\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
  at C:\Applications\AtomDev\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)
```

OS: Windows 10 Pro Insider Preview, Build 10532

Possibly related to the following pull request: https://github.com/atom/atom/pull/8256?

**Comment by abe33** [comment]
Yes it's definitely that, I'm planning to fix that tonight when back home. Say tuned.
