### ISSUE TITLE
Failed to load the minimap-highlight-selected package

### ISSUE THREAD

**Issue by aspot** [atom-minimap/minimap-highlight-selected#17]
[Enter steps to reproduce below:]

1. All I did was launch Atom. It used to work...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package, v4.3.1

### Stack Trace

Failed to load the minimap-highlight-selected package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/alex/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:1:25)
    at Object.<anonymous> (/Users/alex/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "monokai-tweaked-ui",
      "monokai-dark"
    ],
    "disabledPackages": [
      "wrap-guide",
      "block-comment"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
color-picker, v2.0.12
docblockr, v0.7.3
highlight-selected, v0.10.1
minimap, v4.13.4
minimap-highlight-selected, v4.3.1
monokai-dark, v1.3.0
monokai-tweaked-ui, v0.3.0
open-recent, v2.3.0
pigments, v0.15.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi, I'm not sure what could happen, does `event-kit` is properly installed in the packages `node_modules` directory?

**Comment by aspot** [comment]
Hi abe33, I did not see that in the node_modules directory, so I un-installed and re-installed the package and it works now. Thanks!

**Comment by ManuDevil** [comment]
When behind a tough company proxy, how to download the third party _node_modules_ ?
Thank you.
