### ISSUE TITLE
Fail to load package 'highlight-selected'

### ISSUE THREAD

**Issue by Z-Clive** [atom-minimap/minimap-highlight-selected#18]
I'm using **atom 1.0.19** with Windows 10 64bit.

> Could not resolve 'highlight-selected' to a package path

Traceback:

``` javascript
    Error: Failed to load package 'highlight-selected'
        at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Clive\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:494:25)
        at C:\Users\Clive\.atom\packages\minimap-highlight-selected\node_modules\atom-utils\lib\atom-utils.js:29:35
        at Array.forEach (native)
        at C:\Users\Clive\.atom\packages\minimap-highlight-selected\node_modules\atom-utils\lib\atom-utils.js:23:25
        at module.exports.requirePackages (C:\Users\Clive\.atom\packages\minimap-highlight-selected\node_modules\atom-utils\lib\atom-utils.js:8:14)
        at MinimapHighlightSelected.consumeMinimapServiceV1 (C:\Users\Clive\.atom\packages\minimap-highlight-selected\lib\minimap-highlight-selected.coffee:12:5)
        at Provider.module.exports.Provider.provide (C:\Users\Clive\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
        at C:\Users\Clive\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
        at doNTCallback0 (node.js:416:9)
        at process._tickCallback (node.js:345:13)message: "Failed to load package 'highlight-selected'"
```

**Comment by abe33** [comment]
Hi @zmLGBBM, sorry I missed your issue, did you installed the [highlight-selected](https://atom.io/packages/highlight-selected)?

**Comment by zmLGBBM** [comment]
@abe33 Ohhh, that. I just assumed the `highlight-selected` is your `minimap-highlight-selected`. That should work now, thanks haha. I'll be testing this in a few days (I'm on my linux machine for now).
