### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by dcormier** [atom-minimap/minimap-highlight-selected#26]
1. Open file.
2. Hit backspace or delete to try to remove the character before or after the cursor.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Pro
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package, v4.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:872

TypeError: Cannot read property 'push' of undefined
    at file:///C:/Users/[username removed]/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:78:17
    at TextBuffer.module.exports.TextBuffer.scanInRange (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:988:9)
    at TextEditor.module.exports.TextEditor.scanInBufferRange (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2648:26)
    at FakeEditor.(anonymous function) [as scanInBufferRange] (file:///C:/Users/[username removed]/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:18:30)
    at MinimapHighlightSelectedView.handleSelection (file:///C:/Users/[username removed]/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:68:14)
    at MinimapHighlightSelectedView.handleSelection (file:///C:/Users/[username removed]/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at file:///C:/Users/[username removed]/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:94:12
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.selectionRangeChanged (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:2626:27)
    at Selection.module.exports.Selection.markerDidChange (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\selection.js:924:26)
    at C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\display-marker.js:248:27)
    at C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\marker.js:425:20)
    at Marker.module.exports.Marker.update (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\marker.js:366:12)
    at Marker.module.exports.Marker.setHeadPosition (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\marker.js:146:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\display-marker.js:146:32)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\display-marker.js:154:19)
    at C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\cursor.js:668:7)
    at Cursor.module.exports.Cursor.setScreenPosition (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\cursor.js:65:19)
    at Cursor.module.exports.Cursor.moveLeft (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\cursor.js:255:21)
    at C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\selection.js:244:31
    at Selection.module.exports.Selection.modifySelection (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\selection.js:972:7)
    at Selection.module.exports.Selection.selectLeft (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\selection.js:242:19)
    at Selection.module.exports.Selection.backspace (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\selection.js:509:14)
    at C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:1133:26
    at C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:1149:28
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:867:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:1566:26)
    at C:\Users\[username removed]\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:1143:24
```

### Commands

```
     -0:15.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:13 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:09.7.0 core:confirm (input.hidden-input)
  2x -0:03.2.0 core:move-left (input.hidden-input)
     -0:02.7.0 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "language-clojure",
      "language-coffee-script",
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails"
    ],
    "packagesWithKeymapsDisabled": [],
    "restorePreviousWindowsOnStart": false,
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.2.0 (active)
atom-beautify, v0.29.16 (inactive)
editorconfig, v2.1.0 (active)
file-icons, v2.0.8 (active)
go-debug, v1.0.3 (active)
go-plus, v5.1.0 (active)
go-signature-statusbar, v1.2.0 (active)
highlight-selected, v0.12.0 (active)
hyperclick, v0.0.39 (active)
language-batch, v0.3.3 (active)
language-protobuf, v0.7.1 (active)
linter, v1.11.21 (active)
minimap, v4.26.5 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-selection, v4.4.0 (active)
sync-settings, v0.8.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by benweier** [comment]
Also experiencing this issue on Mac OS X (Sierra)

1. Open existing file
2. Double click a word to select it (including the full stack trace because this step is different to @dcormier)

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package, v4.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At /Users/benweier/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:78

TypeError: Cannot read property 'push' of undefined
    at /Users/benweier/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:78:17
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:988:9)
    at TextEditor.module.exports.TextEditor.scanInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2648:26)
    at FakeEditor.(anonymous function) [as scanInBufferRange] (/Users/benweier/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:18:30)
    at MinimapHighlightSelectedView.handleSelection (/Users/benweier/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:68:14)
    at MinimapHighlightSelectedView.handleSelection (/Users/benweier/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /Users/benweier/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:94:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.selectionRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2626:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:924:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:425:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:366:12)
    at Marker.module.exports.Marker.setRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:106:19)
    at DisplayMarker.module.exports.DisplayMarker.setBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:134:32)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:107:24
    at Selection.module.exports.Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:972:7)
    at Selection.module.exports.Selection.setBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:100:19)
    at Selection.module.exports.Selection.selectWord (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:401:12)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:728:42)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
     -0:29.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.paint-cursor.theme-atom-material-syntax-dark.theme-atom-material-ui.has-custom-icons)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-java",
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-property-list",
      "language-ruby-on-rails",
      "language-source",
      "language-sql",
      "language-toml",
      "language-xml",
      "package-generator",
      "styleguide",
      "welcome",
      "wrap-guide",
      "autocomplete-atom-api"
    ],
    "ignoredNames": [
      "node_modules",
      "bower_components",
      ".DS_Store"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "highlight-line"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ],
    "useCustomTitleBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
atom-fix-path, v0.1.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.9 (active)
atom-ternjs, v0.16.1 (active)
auto-update-packages, v1.0.1 (active)
autocomplete-php, v0.3.7 (active)
autocomplete-python, v1.8.26 (active)
change-case, v0.6.3 (active)
docblockr, v0.9.1 (active)
editorconfig, v2.1.0 (active)
emmet, v2.4.3 (active)
file-icons, v2.0.8 (active)
git-plus, v7.1.0 (active)
git-status, v0.3.4 (inactive)
highlight-line, v0.12.0 (active)
highlight-selected, v0.12.0 (active)
language-babel, v2.49.4 (active)
language-pug, v0.0.19 (active)
linter, v1.11.21 (active)
linter-eslint, v8.0.0 (active)
linter-js-yaml, v1.2.6 (inactive)
linter-jsonlint, v1.3.0 (active)
linter-php, v1.3.1 (active)
linter-pug, v1.3.0 (active)
linter-stylelint, v3.7.0 (active)
minimap, v4.26.5 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
minimap-selection, v4.4.0 (active)
pigments, v0.38.0 (active)
project-manager, v3.3.3 (active)
travis-ci-status, v1.3.0 (active)
turbo-javascript, v1.4.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by iggycoder** [comment]
Just to circumvent the error message for now, disable the "highlight selected" feature of minimap

**Comment by greatelv** [comment]
I got a same issue on today..

**Comment by greatelv** [comment]
Many other packages also are suffering similar problem

**Comment by richrace** [comment]
I updated `highlight-selected` package which includes a new API and uses the new MarkerLayer API. This branch https://github.com/atom-minimap/minimap-highlight-selected/tree/feature-highlight-selected-api needs to be merged into master and published.

**Comment by alexrussell** [comment]
Yikes, totally unusable!

**Comment by abe33** [comment]
Hi there, I just published v4.5.0 that includes the enhancements provided by @richrace, let me know if it fixed things for you.

**Comment by MindFreeze** [comment]
fixed it for me

**Comment by dsnellgrove** [comment]
Fixed it on OS X Sierra

**Comment by UziTech** [comment]
fixed it on windows too 👍

**Comment by dcormier** [comment]
Fixed.
