### ISSUE TITLE
Failed to activate the minimap-highlight-selected package

### ISSUE THREAD

**Issue by ndelangen** [atom-minimap/minimap-highlight-selected#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package, v4.5.0

### Stack Trace

Failed to activate the minimap-highlight-selected package

```
At this.highlightSelected.onDidAddSelectedMarker is not a function

TypeError: this.highlightSelected.onDidAddSelectedMarker is not a function
    at MinimapHighlightSelected.init (/Users/dev/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:38:24)
    at MinimapHighlightSelected.init (/Users/dev/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:1:1)
    at MinimapHighlightSelected.consumeHighlightSelectedServiceV1 (/Users/dev/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:14:6)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:377:75)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:194:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:164:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:94:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:831:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "styleguide",
      "package-generator",
      "welcome",
      "metrics",
      "react",
      "language-postcss"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-wallaby, v1.0.14 (inactive)
autocomplete-json, v5.2.0 (inactive)
autocomplete-modules, v1.6.7 (inactive)
git-time-machine, v1.5.4 (inactive)
highlight-selected, v0.11.2 (inactive)
language-ignore, v1.5.2 (inactive)
language-markdown, v0.18.2 (inactive)
language-postcss, v1.3.0 (inactive)
language-svg, v0.9.2 (inactive)
linter, v1.11.18 (inactive)
linter-csslint, v1.3.3 (inactive)
linter-eslint, v8.0.0 (inactive)
linter-jsonlint, v1.3.0 (inactive)
markdown-scroll-sync, v2.1.2 (inactive)
merge-conflicts, v1.4.4 (inactive)
min-ui-colorful, v0.10.0 (inactive)
minimap, v4.25.7 (inactive)
minimap-highlight-selected, v4.5.0 (inactive)
monokai, v0.18.0 (inactive)
one-dark-monokai, v0.2.0 (inactive)
react, v0.16.2 (inactive)
todo-show, v1.9.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by ndelangen** [comment]
Updating the minimap package solved the problem for me

**Comment by maorefaeli** [comment]
have the same problem on windows, 
Atom Version: 1.12.9

**Comment by SavageCore** [comment]
minimap 4.26.6 does not fix this for me

[Enter steps to reproduce below:]

1. Start Atom

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Home
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package, v4.5.0


### Stack Trace

Failed to activate the minimap-highlight-selected package

```
At this.highlightSelected.onDidAddSelectedMarker is not a function

TypeError: this.highlightSelected.onDidAddSelectedMarker is not a function
    at MinimapHighlightSelected.init (file:///C:/Users/Ollie/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:38:24)
    at MinimapHighlightSelected.init (file:///C:/Users/Ollie/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:1:1)
    at MinimapHighlightSelected.consumeHighlightSelectedServiceV1 (file:///C:/Users/Ollie/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:14:6)
    at Provider.module.exports.Provider.provide (C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\service-hub\lib\provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\service-hub\lib\service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:370:75)
    at Package.module.exports.Package.activateNow (C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:187:16)
    at C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:157:32
    at Package.module.exports.Package.measure (C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:92:15)
    at C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:150:26
    at Package.module.exports.Package.activate (C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\Ollie\AppData\Local\atom\app-1.12.9\resources\app.asar\src\atom-environment.js:792:28
```

### Commands

```
     -0:03.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-neutron-ui)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "disabledPackages": [
      "themed-settings",
      "markdown-preview",
      "tab-dropdown",
      "atomizr",
      "remote-sync",
      "tool-bar-config",
      "jslint",
      "fixmyjs"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-beautify",
      "markdown-preview-plus"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "neutron-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ascii-codes, v0.3.3 (inactive)
ask-stack, v2.2.0 (inactive)
atom-beautify, v0.29.16 (inactive)
atom-increment, v0.3.4 (inactive)
atom-meld, v0.2.1 (inactive)
atom-minify, v0.8.0 (inactive)
atom-overtype-mode, v0.3.2 (inactive)
printer, v0.0.0 (inactive)
auto-detect-indentation, v1.3.0 (inactive)
autocomplete-plus, v2.34.2 (inactive)
autoupdate-packages, v1.3.1 (inactive)
clean-context-menu, v0.3.2 (inactive)
click-link, v1.0.9 (inactive)
color-picker, v2.2.4 (inactive)
cson, v2.0.1 (inactive)
css-clean, v2.17.0 (inactive)
dark-flat-ui, v1.2.4 (inactive)
dev-tools-themes, v0.1.3 (inactive)
duplicate-line-or-selection, v0.9.0 (inactive)
editorconfig, v2.0.5 (inactive)
expose, v0.13.0 (inactive)
file-icons, v2.0.8 (inactive)
file-templates, v0.2.0 (inactive)
file-watcher, v0.4.0 (inactive)
fixmyjs, v1.4.0 (inactive)
flex-tool-bar, v0.11.0 (inactive)
foldername-tabs, v0.2.4 (inactive)
git-control, v0.8.2 (inactive)
git-history, v3.2.0 (inactive)
goto, v1.8.2 (inactive)
highlight-line, v0.11.2 (inactive)
highlight-selected, v0.11.2 (inactive)
indent-guide-improved, v1.4.11 (inactive)
intentions, v1.1.2 (inactive)
jslint, v1.5.1 (inactive)
language-batch, v0.3.3 (inactive)
language-bbcode, v0.1.1 (inactive)
language-sln, v0.1.0 (inactive)
language-vb, v0.1.0-pre1 (inactive)
linter, v1.11.18 (inactive)
linter-coffeescript, v1.0.0 (inactive)
linter-csslint, v1.3.3 (inactive)
linter-flake8, v2.1.4 (inactive)
linter-js-yaml, v1.2.6 (inactive)
linter-jshint, v3.0.2 (inactive)
linter-jsonlint, v1.3.0 (inactive)
linter-less, v2.6.0 (inactive)
linter-perlcritic, v1.3.2 (inactive)
linter-php, v1.3.1 (inactive)
linter-xo, v0.21.2 (inactive)
markdown-preview-plus, v2.4.0 (inactive)
markdown-preview-plus-opener, v0.2.0 (inactive)
markdown-scroll-sync, v2.1.2 (inactive)
metrics, v1.1.2 (inactive)
minimap, v4.26.6 (inactive)
minimap-bookmarks, v0.4.2 (inactive)
minimap-cursorline, v0.2.0 (inactive)
minimap-find-and-replace, v4.5.1 (inactive)
minimap-git-diff, v4.3.1 (inactive)
minimap-highlight-selected, v4.5.0 (inactive)
minimap-linter, v1.6.0 (inactive)
minimap-pigments, v0.2.2 (inactive)
neutron-syntax, v0.7.0 (inactive)
neutron-ui, v0.4.0 (inactive)
nucleus-dark-ui, v0.10.19 (inactive)
open-recent, v5.0.0 (inactive)
package-reloader, v1.0.0 (inactive)
php-cs-fixer, v4.1.0 (inactive)
pigments, v0.37.0 (inactive)
process-palette, v0.10.0 (inactive)
project-viewer, v0.3.42 (inactive)
red-wavy-underline, v0.3.0 (inactive)
regex-railroad-diagram, v0.16.0 (inactive)
Remote-FTP, v0.9.4 (inactive)
revert-buffer, v0.5.0 (inactive)
script, v3.14.0 (inactive)
sequential-number, v0.4.0 (inactive)
simple-drag-drop-text, v0.3.1 (inactive)
smart-tags, v0.1.5 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (inactive)
sync-settings, v0.8.1 (inactive)
synced-sidebar, v0.4.3 (inactive)
tab-title, v0.3.3 (inactive)
tabletopsimulator-lua, v1.1.7 (inactive)
todo-show, v1.9.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
tool-bar, v1.0.1 (inactive)
tree-view-git-status, v1.3.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.34.2 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by richrace** [comment]
You need Atom 1.13

**Comment by Xcodo** [comment]
Atom 1.13 isn't being shown as an available update for me yet (though I saw the announcement).

Couldn't breaking versions <1.13 be prevented with package.json?
```
"engines": {
    "atom": ">0.50.0"
  }
```

**Comment by SavageCore** [comment]
Thanks, manually installed 1.13 and all is well.

**Comment by richrace** [comment]
This package requires a compatible version of `highlight-selected`; the latest version of this package requires the latest version of `highlight-selected` that requires Atom 1.13 (https://github.com/richrace/highlight-selected/blob/master/package.json#L12) 

Going forward it will be easier to deal with breaking changes as `highlight-selected` now implements a API which `minimap-highlight-selected` consumes.

**Comment by gizzygizmo** [comment]
I have 1.13, and highlight-selected 0.12.0... still throws error; tried re-installing both packages same issue.

<code>[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package, v4.5.0


### Stack Trace

Failed to activate the minimap-highlight-selected package

```
At this.highlightSelected.onDidAddSelectedMarker is not a function

TypeError: this.highlightSelected.onDidAddSelectedMarker is not a function
    at MinimapHighlightSelected.init (/Users/istein001/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:38:24)
    at MinimapHighlightSelected.init (/Users/istein001/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:1:1)
    at MinimapHighlightSelected.activatePlugin (/Users/istein001/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:33:6)
    at Main.activatePlugin (/Users/istein001/.atom/packages/minimap/lib/mixins/plugin-management.js:187:12)
    at Main.updatesPluginActivationState (/Users/istein001/.atom/packages/minimap/lib/mixins/plugin-management.js:171:14)
    at /Users/istein001/.atom/packages/minimap/lib/mixins/plugin-management.js:241:12
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:616:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at Main.registerPluginControls (/Users/istein001/.atom/packages/minimap/lib/mixins/plugin-management.js:240:53)
    at Main.registerPlugin (/Users/istein001/.atom/packages/minimap/lib/mixins/plugin-management.js:83:12)
    at MinimapHighlightSelected.consumeMinimapServiceV1 (/Users/istein001/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:11:14)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:377:75)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:194:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:164:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:94:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:299:11)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:329:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -2:16.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:27.7.0 core:confirm (input.hidden-input)
     -0:52.5.0 core:backspace (input.hidden-input)
     -0:52.3.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-atom-api",
      "autocomplete-css",
      "autocomplete-plus"
    ],
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1 (active)
atom-material-syntax, v0.4.6 (inactive)
auto-indent, v0.5.0 (active)
editor-stats, v0.17.0 (active)
file-icons, v2.0.8 (active)
highlight-line, v0.11.2 (active)
highlight-selected, v0.12.0 (active)
indent-guide-improved, v1.4.11 (active)
language-diff, v0.6.0 (active)
language-yang, v0.2.0 (active)
minimap, v4.25.7 (active)
minimap-highlight-selected, v4.5.0 (inactive)
project-manager, v3.3.3 (active)
release-notes, v0.53.0 (active)
split-diff, v1.1.0 (inactive)
sublime-block-comment, v0.4.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
sync-settings, v0.8.1 (active)
tab-length, v0.1.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

</code>

**Comment by gizzygizmo** [comment]
Seems to have fixed itself, after uninstalling this package.  Installing several others, then going back and installing highlighted again.

**Comment by posita** [comment]
Uninstalling, restarting, then reinstalling did *_not_* solve the issue for me.

**Comment by lmj0011** [comment]
for ubuntu 16.04 users who installed Atom from webupd8, just upgrade Atom to v1.13.0 to get rid of the error

```sh
$ sudo apt update

$ sudo apt upgrade

$ atom -v 
```


ref: http://ppa.launchpad.net/webupd8team/atom/ubuntu/pool/main/a/atom/
