### ISSUE TITLE
Failed to activate the minimap-highlight-selected package

### ISSUE THREAD

**Issue by yousung** [atom-minimap/minimap-highlight-selected#30]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Unknown Windows Version
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package, v4.5.0

### Stack Trace

Failed to activate the minimap-highlight-selected package

```
At this.highlightSelected.onDidAddSelectedMarker is not a function

TypeError: this.highlightSelected.onDidAddSelectedMarker is not a function
    at MinimapHighlightSelected.init (file:///C:/Users/one-1pc/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:38:24)
    at MinimapHighlightSelected.init (file:///C:/Users/one-1pc/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:1:1)
    at MinimapHighlightSelected.consumeHighlightSelectedServiceV1 (file:///C:/Users/one-1pc/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:14:6)
    at Provider.module.exports.Provider.provide (C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\service-hub\lib\provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:377:75)
    at Package.module.exports.Package.activateNow (C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:194:16)
    at C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:164:32
    at Package.module.exports.Package.measure (C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:94:15)
    at C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:157:26
    at Package.module.exports.Package.activate (C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\one-1pc\AppData\Local\atom\app-1.13.0\resources\app.asar\src\atom-environment.js:831:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "file-icon-supplement",
      "activate-power-mode",
      "split-diff",
      "atom-bootstrap3",
      "tree-view-git-status",
      "atom-autocomplete-php"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (inactive)
angular2-snippets, v0.3.0 (inactive)
angularjs, v0.3.5 (inactive)
atom-autocomplete-php, v0.21.0 (inactive)
atom-beautify, v0.29.16 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
atom-jade, v0.3.0 (inactive)
atom-runner, v2.7.1 (inactive)
atom-ternjs, v0.16.1 (inactive)
atom-typescript, v10.1.13 (inactive)
atomic-chrome, v0.3.0 (inactive)
auto-encoding, v0.6.2 (inactive)
autoclose-html, v0.23.0 (inactive)
autocomplete-paths, v1.0.5 (inactive)
autocomplete-php, v0.3.7 (inactive)
codeigniter, v0.3.1 (inactive)
color-picker, v2.2.4 (inactive)
docblockr, v0.9.1 (inactive)
emmet, v2.4.3 (inactive)
file-icon-supplement, v0.8.3 (inactive)
format-sql, v0.3.0 (inactive)
git-commit, v1.5.3 (inactive)
git-plus, v7.0.7 (inactive)
goto-last-edit, v0.3.2 (inactive)
highlight-selected, v0.11.2 (inactive)
javascript-snippets, v1.2.1 (inactive)
linter, v1.11.18 (inactive)
linter-csslint, v1.3.3 (inactive)
linter-eslint, v8.0.0 (inactive)
linter-htmlhint, v1.3.1 (inactive)
linter-jshint, v3.0.2 (inactive)
linter-php, v1.3.1 (inactive)
livereload, v0.4.4 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.25.7 (inactive)
minimap-cursorline, v0.2.0 (inactive)
minimap-find-and-replace, v4.5.1 (inactive)
minimap-hide, v0.3.0 (inactive)
minimap-highlight-selected, v4.5.0 (inactive)
minimap-selection, v4.4.0 (inactive)
permanent-delete, v0.1.5 (inactive)
project-manager, v3.3.3 (inactive)
react, v0.16.2 (inactive)
Remote-FTP, v0.9.4 (inactive)
script, v3.14.0 (inactive)
split-diff, v1.1.0 (inactive)
sync-settings, v0.8.1 (inactive)
todo-show, v1.9.0 (inactive)
tree-view-git-status, v1.3.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by yousung** [comment]
I made an update and solved it.

**Comment by visualcookie** [comment]
Still having the problem... even after update.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: HPAVDEAN
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package, v4.5.0


### Stack Trace

Failed to activate the minimap-highlight-selected package

```
At this.highlightSelected.onDidAddSelectedMarker is not a function

TypeError: this.highlightSelected.onDidAddSelectedMarker is not a function
    at MinimapHighlightSelected.init (file:///C:/Users/dean/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:38:24)
    at MinimapHighlightSelected.init (file:///C:/Users/dean/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:1:1)
    at MinimapHighlightSelected.consumeHighlightSelectedServiceV1 (file:///C:/Users/dean/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:14:6)
    at Provider.module.exports.Provider.provide (C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\service-hub\lib\provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:377:75)
    at Package.module.exports.Package.activateNow (C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:194:16)
    at C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:164:32
    at Package.module.exports.Package.measure (C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:94:15)
    at C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:157:26
    at Package.module.exports.Package.activate (C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\dean\AppData\Local\atom\app-1.13.0\resources\app.asar\src\atom-environment.js:831:28
```

### Commands

```
     -0:00.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-gloom.theme-clean-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Remote-FTP",
      "atom-beautify"
    ],
    "packagesWithKeymapsDisabled": [],
    "projectHome": "G:\\work\\development",
    "restorePreviousWindowsOnStart": false,
    "telemetryConsent": "limited",
    "themes": [
      "clean-ui",
      "gloom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.5.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.9 (inactive)
atom-panda-syntax, v0.16.0 (inactive)
bezier-curve-editor, v0.7.2 (inactive)
change-tabs, v0.2.0 (inactive)
clean-ui, v1.8.2 (inactive)
color-picker, v2.2.4 (inactive)
docblockr, v0.9.1 (inactive)
duotone-dark-sea-syntax, v2.0.1 (inactive)
duotone-dark-space-syntax, v2.0.1 (inactive)
duotone-dark-syntax, v2.0.1 (inactive)
editorconfig, v2.1.0 (inactive)
emmet, v2.4.3 (inactive)
file-icons, v2.0.8 (inactive)
firewatch-syntax, v1.0.1 (inactive)
git-plus, v7.0.7 (inactive)
gloom, v0.4.0 (inactive)
hacking-the-kernel, v1.6.1 (inactive)
hacking-the-kernel-ui, v1.6.0 (inactive)
highlight-line, v0.11.2 (inactive)
highlight-selected, v0.11.2 (inactive)
iceberg-syntax, v0.2.2 (inactive)
language-blade, v0.26.3 (inactive)
language-pug, v0.0.19 (inactive)
language-twig, v1.6.3 (inactive)
language-vue, v0.21.1 (inactive)
linter, v1.11.18 (inactive)
linter-eslint, v8.0.0 (inactive)
linter-php, v1.3.1 (inactive)
linter-pug, v1.3.0 (inactive)
linter-sass-lint, v1.7.4 (inactive)
minimap, v4.25.7 (inactive)
minimap-highlight-selected, v4.5.0 (inactive)
one-dark-vivid-syntax, v1.5.0 (inactive)
pigments, v0.37.0 (inactive)
project-plus, v0.9.0 (inactive)
sync-settings, v0.8.1 (inactive)
tabs-to-spaces, v1.0.3 (inactive)
todo-show, v1.9.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by richrace** [comment]
You need to update `highlight-selected`

**Comment by visualcookie** [comment]
Yeah, works now. :)

**Comment by natcl** [comment]
I have the same issue and all my packages are updated :/

**Comment by natcl** [comment]
Nevermind, was not updated to 1.13

**Comment by greenais** [comment]
No mentioned updates available, the latest Atom reports:
Atom - 1.12.9
highlight-selected - 0.1.12
minimap-highlight-selected - 4.5.0

So Atom reports that verything is up-to-date, but minimap-highlight-selected still fails to start.
What's wrong, guys?

**Comment by dutch92** [comment]
Atom throws this error, but minimap-highlight-selected works fine

**Comment by EQuimper** [comment]
+ 1

**Comment by rainboxx** [comment]
@dutch92: Updating Atom manually (by clicking "Install updates and restart" or similar from the menu), checking for outdated packages, updating and restarting Atom solved this issue for me.

**Comment by JLCCI** [comment]
I get this error every time and reinstalling the package or updating does not solve it. Sometimes I wish Atom development froze so I don't have to deal with breakage so much..

Thanks for addressing the issue!

**Comment by jlojosnegros** [comment]
Same here ... 

plugin is updated to the last version but still crash

**Comment by pwaller** [comment]
@jlojosnegros I had the same confusion but the confusing thing here is that you need to update to the latest **atom** (1.13), **not** the version of this plugin.

**Comment by dutch92** [comment]
my OS is Elementary based on Ubuntu and the latest version of atom is 1.12.6. Atom does not suggest me to upgrade to the version 1.13

**Comment by justinmueller** [comment]
Being  `highlight-selected` didn't fully update until I had Atom 1.13 it would probably be beneficial to do the same thing with this update being it is dependent. (Unless it was just a fluke I didn't get the update until after having 1.13.)

**Comment by igneosaur** [comment]
I am also running Linux and my latest version of Atom is 1.12.7. I don't see how you can mark this closed when it is still throws errors on one platform.

**Comment by DanielAndreasen** [comment]
To solve this I first upgraded Atom (I have 1.13.0 now), then update all the packages. Only after the update and a restart of Atom this error is gone.

**Comment by Manish-Giri** [comment]
Same error after Atom update.

**Comment by shmee46** [comment]
I solve the problem by updating Atom IDE to the most current one which is 1.13.0, then update minimap to 4.26.7, and finally update the minimap-highlight-selected to 4.5.0. Hope this helps.

**Comment by misterbridge** [comment]
On Linux 1.13.1 is available on atom.io website, just download the latest .deb (I did not test the .rpm, I'm on Ubuntu)

**Comment by IvanLisz** [comment]
Failed to activate the minimap-highlight-selected package
this.highlightSelected.onDidAddSelectedMarker is not a function
Hide Stack Trace
TypeError: this.highlightSelected.onDidAddSelectedMarker is not a function
    at MinimapHighlightSelected.init (/home/ivan/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:38:24)
    at MinimapHighlightSelected.init (/home/ivan/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:1:1)
    at MinimapHighlightSelected.consumeHighlightSelectedServiceV1 (/home/ivan/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:14:6)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:377:75)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:194:16)
    at /usr/share/atom/resources/app.asar/src/package.js:164:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:94:15)
    at /usr/share/atom/resources/app.asar/src/package.js:157:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:550:34)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:508:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:831:28


Same issue here. latest atom version.
