### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by AlexWayfer** [atom-minimap/minimap-highlight-selected#49]
[Enter steps to reproduce:]

1. Just open a project.

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: "Arch Linux"
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package 4.6.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_cwd

```
At internal/process/main_thread_only.js:42

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/usr/lib/atom/node_modules/graceful-fs/polyfills.js:10:19)
    at process.cwd (/packages/minimap-highlight-selected/node_modules/graceful-fs/polyfills.js:11:19)
    at process.cwd (/usr/lib/atom/node_modules/graceful-fs/polyfills.js:10:19)
    at process.cwd (/packages/go-plus/node_modules/graceful-fs/polyfills.js:10:19)
    at Object.default (/packages/linter-remark/node_modules/libnpmconfig/index.js:19:33)
    at pudGet (/packages/linter-remark/node_modules/figgy-pudding/index.js:122:28)
    at FiggyPudding.get (/packages/linter-remark/node_modules/figgy-pudding/index.js:27:12)
    at Object.get (/packages/linter-remark/node_modules/figgy-pudding/index.js:159:16)
    at getNpmConfig (/packages/linter-remark/node_modules/libnpmconfig/index.js:50:72)
    at /packages/linter-remark/node_modules/load-plugin/index.js:31:17)
    at /packages/linter-remark/node_modules/load-plugin/index.js:143:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/linter-remark/node_modules/unified-engine/lib/configuration.js:8:15)
    at /packages/linter-remark/node_modules/unified-engine/lib/configuration.js:291:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/linter-remark/node_modules/unified-engine/lib/file-set-pipeline/configure.js:3:21)
    at /packages/linter-remark/node_modules/unified-engine/lib/file-set-pipeline/configure.js:11:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/linter-remark/node_modules/unified-engine/lib/file-set-pipeline/index.js:4:17)
    at /packages/linter-remark/node_modules/unified-engine/lib/file-set-pipeline/index.js:17:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/linter-remark/node_modules/unified-engine/lib/index.js:5:23)
    at /packages/linter-remark/node_modules/unified-engine/lib/index.js:153:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/linter-remark/node_modules/unified-engine-atom/index.js:9:14)
    at /packages/linter-remark/node_modules/unified-engine-atom/index.js:142:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at linterRemarkLoadDependencies (/packages/linter-remark/index.js:81:14)
    at callback (/packages/linter-remark/index.js:92:5)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-smart-tabs 0.1.0 
atom-typescript 14.0.3 
auto-detect-indentation 1.3.0 
auto-update-plus 0.5.8 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.5 
autocomplete-ruby 0.2.8 
autocomplete-ruby-rct 0.1.0 
autoupdate-packages 1.3.1 
ax-monokai-syntax 0.3.0 
better-git-blame 0.5.0 
blocky 0.13.0 
busy-signal 2.0.1 
change-line-length 0.1.1 
chmod 0.1.1 
color-picker 2.3.0 
editorconfig 2.6.1 
file-icons 2.1.44 
file-watcher 2.0.0 
genesis-ui 0.5.0 
git-time-machine 2.1.0 
go-plus 6.1.0 
goto-definition 1.3.4 
highlight-selected 0.17.0 
hyperclick 0.1.5 
ide-crystal 0.3.3 
ide-ruby 0.5.0 
ide-yaml 0.7.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-crystal-actual 0.37.2 
language-docker 1.1.8 
language-fish-shell 1.1.0 
language-haml 0.32.1 
language-markdown 0.37.0 
language-nginx 0.8.0 
language-postcss 1.3.1 
language-systemd 0.1.1 
language-typescript-react 0.1.1 
language-vue 0.26.0 
linter 3.1.1 
linter-erb 1.1.5 
linter-eslint 8.5.5 
linter-htmlhint 1.6.3 
linter-jshint 3.1.19 
linter-markdown 5.2.11 
linter-reek 2.4.2 
linter-remark 9.0.0 
linter-rubocop 2.5.7 
linter-ruby 1.3.1 
linter-slim 2.0.0 
linter-spell 0.15.0 
linter-spell-ruby 0.4.0 
linter-stylelint 4.5.1 
linter-ui-default 2.1.4 
linter-ui-plus 0.3.2 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
monocolor-blue-syntax 2.0.0 
monokai 0.26.0 
monokai-flat 1.0.1 
monokai-plus 0.1.3 
monokai-pro 0.1.0 
monokai-slate 0.6.0 
monokai-sublime 1.0.0 
nord-atom-syntax 0.10.0 
northem-atom-syntax 2.1.0 
northem-dark-atom-syntax 2.1.0 
nucleus-dark-ui 0.12.3 
one-monokai 0.3.0 
pascal 1.2.1 
platformio-ide-terminal 2.10.0 
precss 0.3.0 
remember-file-positions 0.2.3 
revert-buffer 0.6.0 
robe 0.4.3 
ruby-block 0.3.6 
ruby-block-converter 4.1.1 
ruby-define-method 0.2.2 
ruby-navigator 0.5.0 
ruby-slim 0.2.0 
ruby-test 1.0.2 
scroll-editor-on-middle-click 0.7.0 
seeing-is-believing 15.0.0 
seti-icons 1.5.4 
seti-ui 1.11.0 
single-click-open 0.2.2 
slim-language 2.2.0 
space-tab 0.4.2 
space-underscore 0.1.1 
split-diff 1.6.1 
stacked-tabs 0.1.3 
symbols-tree-view 0.14.0 
sync-settings 5.0.7 
tab-control 0.6.11 
tabs-to-spaces 1.0.5 
tasks 2.10.1 
teletype 0.13.4 
term3 0.22.1 
toggle-quotes 1.1.4 
tree-view-open-files 0.3.0 
wrap-with-anything 0.1.1 
yaml-path 0.1.1 
yard 0.5.1 
zentabs 0.8.9 
```

**Comment by AlexWayfer** [comment]
> @UziTech closed this 7 hours ago

Ehm, why?

**Comment by UziTech** [comment]
Trying to clean up issues. This doesn't seem like something this package can fix. Based on the error stack it seems like this is an issue with Atom not this package.
