### ISSUE TITLE
Highlight Selected Update

### ISSUE THREAD

**Issue by richrace** [atom-minimap/minimap-highlight-selected#7]
I've made some changes and not sure if they'll effect this package. 

When I merge it and publish; the `HighlightSelected` package will be `v0.10.0`

https://github.com/richrace/highlight-selected/pull/60

**Comment by xeron** [comment]
Looks like they do.

It completely brakes atom, I'm even not able to open setting and have to remove highlight or minimap-highlight package using amp/rm -rf.

I'm not sure if it's highlight or minimap-highlight issue. Stack trace:
```
/Users/xeron/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:30
Hide Stack Trace
TypeError: undefined is not a function
  at MinimapHighlightSelectedView.module.exports.HighlightedAreaView.subscribeToActiveTextEditor (/Users/xeron/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:30:70)
  at /Users/xeron/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:13:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:338:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:213:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:277:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app/src/pane.js:271:19)
  at Pane.module.exports.Pane.activateNextItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:232:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:349:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:421:16)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:398:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:582:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:621:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:307:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)
```

**Comment by richrace** [comment]
Ok. I'll hold of merging it until it doesn't break this package :+1:

**Comment by xeron** [comment]
Actually I see this issue with 0.9.2.
